# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestcheckoutcheckoutculogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testcheckoutcheckoutculogin(self):
    # Test name: test_checkout checkout cu login
    # Step # | name | target | value
    # 1 | open | /en/ | 
    self.driver.get("https://prestashop-ta26.multibit.ro/en/")
    # 2 | setWindowSize | 1070x824 | 
    self.driver.set_window_size(1070, 824)
    # 3 | click | css=a > .hidden-sm-down | 
    self.driver.find_element(By.CSS_SELECTOR, "a > .hidden-sm-down").click()
    # 4 | type | id=field-email | alexandra.iuganu@gmail.com
    self.driver.find_element(By.ID, "field-email").send_keys("alexandra.iuganu@gmail.com")
    # 5 | type | id=field-password | ALEXANDRA.2023
    self.driver.find_element(By.ID, "field-password").send_keys("ALEXANDRA.2023")
    # 6 | click | id=field-email | 
    self.driver.find_element(By.ID, "field-email").click()
    # 7 | click | id=field-password | 
    self.driver.find_element(By.ID, "field-password").click()
    # 8 | click | css=.form-footer | 
    self.driver.find_element(By.CSS_SELECTOR, ".form-footer").click()
    # 9 | click | id=submit-login | 
    self.driver.find_element(By.ID, "submit-login").click()
    # 10 | click | css=.logo | 
    self.driver.find_element(By.CSS_SELECTOR, ".logo").click()
    # 11 | click | css=.js-product:nth-child(1) img | 
    self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(1) img").click()
    # 12 | click | css=.add-to-cart | 
    self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
    # 13 | click | css=.cart-content-btn > .btn-primary | 
    self.driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-primary").click()
    # 14 | close |  | 
    self.driver.close()
  
