# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestProdusemultiple():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_produsemultiple(self):
    # Test name: produse_multiple
    # Step # | name | target | value
    # 1 | open | /en/ | 
    self.driver.get("https://prestashop-ta26.multibit.ro/en/")
    # 2 | setWindowSize | 1070x824 | 
    self.driver.set_window_size(1070, 824)
    # 3 | click | css=.js-product:nth-child(2) img | 
    self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(2) img").click()
    # 4 | click | id=group_1 | 
    self.driver.find_element(By.ID, "group_1").click()
    # 5 | select | id=group_1 | label=M
    dropdown = self.driver.find_element(By.ID, "group_1")
    dropdown.find_element(By.XPATH, "//option[. = 'M']").click()
    # 6 | click | css=.add-to-cart | 
    self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
    # 7 | click | css=.cart-content-btn > .btn-secondary |
    self.driver.implicitly_wait(5)
    self.driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-secondary").click()
    # 8 | click | css=.logo | 
    self.driver.find_element(By.CSS_SELECTOR, ".logo").click()
    # 9 | click | css=.js-product:nth-child(6) img | 
    self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(6) img").click()
    # 10 | click | css=.touchspin-up | 
    self.driver.find_element(By.CSS_SELECTOR, ".touchspin-up").click()
    # 11 | click | css=.add-to-cart | 
    self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
    # 12 | click | css=.cart-content-btn > .btn-primary | 
    self.driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-primary").click()
  
