# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestAddtocart():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_addtocart(self):
        self.driver.get("https://prestashop-ta26.multibit.ro/en/")
        self.driver.set_window_size(1068, 824)
        self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(3) img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
        checkout_button = WebDriverWait(self.driver, 15).until(
            lambda d: d.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-primary"))
        checkout_button.click()
